options {
   directory "/var/cache/bind";
   recursion yes;
   allow-query { any; };
   forwarders { 8.8.8.8; 1.1.1.1; };
   dnssec-validation no;
   listen-on { any; };
};



zone "risecup.lan" {
   type master;
   file "/etc/bind/zonas/db.risecup.lan";
};
